basePath: /
host: localhost:9999
info:
  contact:
    email: emikohmann@gmail.com
    name: Emiliano Kohmann
    url: https://www.linkedin.com/in/emilianokohmann/
  description: This is an API that handles the admin commands.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.linkedin.com/in/emilianokohmann/
  title: Admin API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
