basePath: /
definitions:
  admin.DockerAdditionalInfo:
    additionalProperties: true
    type: object
  http.APIErrorHTTP:
    properties:
      message:
        example: Some information not found
        type: string
      status:
        example: 404
        type: integer
    type: object
  http.GetServiceResponseHTTP:
    properties:
      additional_info:
        $ref: '#/definitions/admin.DockerAdditionalInfo'
      creation_date:
        example: "2023-03-29T03:36:19Z"
        type: string
      health:
        example: HEALTHY
        type: string
      name:
        example: Items API
        type: string
      network:
        example: shop_default
        type: string
      port:
        example: 8080
        type: integer
      status:
        example: RUNNING
        type: string
      status_detail:
        example: Up 2 hours
        type: string
      version:
        example: 0.0.1
        type: string
    type: object
  http.ListServicesResponseHTTP:
    properties:
      services:
        items:
          $ref: '#/definitions/http.ServiceResponseHTTP'
        type: array
    type: object
  http.ServiceResponseHTTP:
    properties:
      creation_date:
        example: "2023-03-29T03:36:19Z"
        type: string
      health:
        example: HEALTHY
        type: string
      name:
        example: Items API
        type: string
      network:
        example: shop_default
        type: string
      port:
        example: 8080
        type: integer
      status:
        example: RUNNING
        type: string
      status_detail:
        example: Up 2 hours
        type: string
      version:
        example: 0.0.1
        type: string
    type: object
host: localhost:9999
info:
  contact:
    email: emikohmann@gmail.com
    name: Emiliano Kohmann
    url: https://www.linkedin.com/in/emilianokohmann/
  description: This is an API that handles the admin commands.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.linkedin.com/in/emilianokohmann/
  title: Admin API
  version: "1.0"
paths:
  /services:
    get:
      description: Return the services information fetching information from the configuration
        and Docker.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.ListServicesResponseHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.APIErrorHTTP'
      summary: Return the list of current services.
      tags:
      - Admin
  /services/{serviceID}:
    get:
      description: Return the service information fetching information from the configuration
        and Docker.
      parameters:
      - description: ID of the service to get
        in: path
        name: serviceID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.GetServiceResponseHTTP'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.APIErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.APIErrorHTTP'
      summary: Return the service information.
      tags:
      - Admin
schemes:
- http
swagger: "2.0"
