{
 "title": "Items API",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Items - GET",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(items_get[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Items - GET",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "items_get", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Items - LIST",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(items_list[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Items - LIST",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "items_list", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Items - SAVE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(items_save[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Items - SAVE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "items_save", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Items - UPDATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(items_update[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Items - UPDATE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "items_update", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Items - DELETE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(items_delete[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Items - DELETE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "items_delete", "legendFormat": "__auto" }
   ]
  }
 ]
}