// Code generated by mockery v2.22.1. DO NOT EDIT.

package users

import (
	context "context"
	users "users-api/pkg/users"

	mock "github.com/stretchr/testify/mock"
)

// UsersMetrics is an autogenerated mock type for the usersMetrics type
type UsersMetrics struct {
	mock.Mock
}

// NotifyMetric provides a mock function with given fields: ctx, action
func (_m *UsersMetrics) NotifyMetric(ctx context.Context, action users.Action) {
	_m.Called(ctx, action)
}

type mockConstructorTestingTNewUsersMetrics interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsersMetrics creates a new instance of UsersMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsersMetrics(t mockConstructorTestingTNewUsersMetrics) *UsersMetrics {
	mock := &UsersMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
